Learning fastAPI / firts steps for fastAPI
Valenby/favorite_anime pull request #1
Opened 2024-01-04 23:32 UTC by Valenby

`this requests is for create a API that it have or return my favorite animes.
`

2024-01-04 23:42 UTC, juancarestre commented
Porfavor arranca esta API en tu local, pruebala primero y crea un readme que me diga como podria probarla yo porfavor, el codigo lo veo bien de momento, pero faltaria esto ultimo para yo darle el approve

2024-01-05 00:06 UTC, Valenby commented
> Porfavor arranca esta API en tu local, pruebala primero y crea un readme que me diga como podria probarla yo porfavor, el codigo lo veo bien de momento, pero faltaria esto ultimo para yo darle el approve

Ya realice los cambios, los revisas por favor?

2024-01-05 00:10 UTC, juancarestre requested changes
el archivo __pycache__ sobra, porfa añade un gitignore para ignorar esos archivos y vuelvelo a subir sin esos archivos en __pycache__

2024-01-05 00:10 UTC, juancarestre commented on __pycache__/file.cpython-312.pyc
este archivo sobra, porfavor crea un .gitignore para estos archivos

2024-01-05 00:13 UTC, Valenby commented on __pycache__/file.cpython-312.pyc
listo

2024-01-05 00:15 UTC, juancarestre approved these changes
Todo esta bien, buen trabajo jeje te amo

2024-01-05 00:15 UTC, merged